version: '3'

services:
  mongo:
    image: mongo:4.4
    container_name: "mongo4_4-standalone"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dev-test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 17017:27017
    volumes: 
      # - ./standalone-data:/data/db 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro