version: "3.3"
services:
  zero:
    container_name: zero
    image: dgraph/dgraph:latest
    volumes:
      - ./data:/dgraph
    ports:
      - 15080:5080
      - 16080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080 --replicas=1

  alpha:
    container_name: alpha1
    image: dgraph/dgraph:latest
    volumes:
      - ./data:/dgraph
    ports:
      - 18080:8080
      - 19080:9080
      - 18000:8000
    restart: on-failure
    command: dgraph alpha --security "whitelist=0.0.0.0/0" --my=alpha1:7080 --zero=zero:5080
